### ISSUE TITLE
[AMELIORATION]   Changement de canaux de développement par l'utilisateur

### ISSUE THREAD

**Issue by Colveri** [e-psi-lon/menu-self#1]
Voici ma proposition :

Si le choix du canal de développement de l'appli est changé. Une requête est envoyée pour voir si l'application est différente. Je pense notamment aux changements entre le canal stable et les trois autres dont les versions seront très certainement différentes.

**_C'est donc :_**
On avertit l'utilisateur que l'application est sur le point d'être modifiée. S'il choisi de poursuivre, la mise à jour se fait selon le canal qu'il a sélectionné. Si il refuse, rien ne se fait et le changement de canal est annulé.

**Comment by e-psi-lon** [comment]
C'est une bonne idée. Tu souhaitais la faire me semblait il. Je te l'ai donc assigné (ainsi qu'à moi-même au cas où) j'attends donc ta pull request. 
Après je souhaite limiter le plus possible les requêtes, car c'est une appli pour un simple menu, cela serait idiot qu'elle consomme toute les données mobiles de l'utilisateur (d'ailleurs je devrais peut être rajouter une sécurité sur les boutons qui nécessitent des requêtes)

**Comment by Colveri** [comment]
Yes, faut que je m'en charge ! Juste que je m'entraine au Kotlin un piti peu !

**Comment by e-psi-lon** [comment]
> Yes, faut que je m'en charge ! Juste que je m'entraine au Kotlin un piti peu !

Effectivement ça serait pratique

**Comment by Colveri** [comment]
**IDÉE POUR REDUIRE LES REQUÊTES**

Chaque jour, faire une requête puis stocker le menu de la semaine dans un fichier texte (ou autre, à voir).

À partir de la ça ferait une requête par jour au lieu de possiblement plusieures tout en mettant le menu à jour si il y a des changements de dernière minute.

**Comment by e-psi-lon** [comment]
Bon ben du coup les 2 sont faits, j'aimerais bosser sur le rework en Kotlin Multiplatform.
