### ISSUE TITLE
[BUG] Bugs visuels connexion Pronote

### ISSUE THREAD

**Issue by Colveri** [e-psi-lon/menu-self#2]
1. Lorsque l'on entre ses identifiants Pronote, si la connexion n'a pas pu se faire, le switch reste en position comme si l'utilisateur est connecté (comme voir image même si le screen n'est pas issu de l'application Menu du Self)
![image_2023-10-16_202154147](https://github.com/e-psi-lon/menu-self/assets/123240579/38ca766d-f2ed-4a09-a1e5-72ecd2b0cb0c)

2. La zone pour entres les identifiants est très petite et "difficile" d'accès. Il faudrait peut être revoir la mise en page de la pop-up de connexion.

**Comment by e-psi-lon** [comment]
1. Effectivement, c'est problématique. Je corrigerai ça dès que possible
2. Ce bug-ci m'était connu, il devrait être fixé  d'ici le prochain build de dev. Pour ce qui est des builds alpha, beta et release, il faudra attendre un peu

**Comment by e-psi-lon** [comment]
Fixé en local, push bientôt

**Comment by Colveri** [comment]
> Fixé en local, push bientôt

Super !
