### ISSUE TITLE
Petit souci dans les repas du mardi soir

### ISSUE THREAD

**Issue by Colveri** [e-psi-lon/menu-self#3]
![Screenshot_20240115_184137_fr.e_psi_lon.menuself.jpg](https://github.com/e-psi-lon/menu-self/assets/123240579/c3df3e0e-d4d5-435e-908b-ce8a188e7e51)

![Screenshot_20240115_184139_fr.e_psi_lon.menuself.jpg](https://github.com/e-psi-lon/menu-self/assets/123240579/d4696aa6-a6d4-4617-87cf-6a0c100f8352)

![Screenshot_20240115_184145_com.android.chrome.jpg](https://github.com/e-psi-lon/menu-self/assets/123240579/08e5db5b-6a95-4a72-92b9-f4bbdc218dd9)

**Comment by e-psi-lon** [comment]
Wtf comment est-ce possible, ils ont touchés à des trucs ou quoi ? Bon ben je vais passer sur l'autre site, il est beaucoup plus simpliste donc moins de trucs à parser. Et de toute façon je suis en train de tout refaire [(repo privée)](https://github.com/e-psi-lon/menu-self2) donc je vais modifier les 2 ça sera fait. Et je ferais une release ici du coup

**Comment by Colveri** [comment]
Ok, eh par contre tu m'as mis dans ta repo ouuuu ? parce que je vois tout

**Comment by e-psi-lon** [comment]
Oups j'ai pas mis en privé la boulette

**Comment by Colveri** [comment]
T'arrives pas à régler ?

**Comment by e-psi-lon** [comment]
Fixé dans la release v1.2(.1) avec un rework complet du système de fetch/parse du menu & la possibilité de changer le menu
Et si j'avais réglé mais je pensais rollback un truc mais au final c'est bon j'ai réouvert pour rien

**Comment by Colveri** [comment]
Okay, je viens de maj et c'est bien bon. Super merci !

**Comment by e-psi-lon** [comment]
Nickel
